modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Academic Free License v3.0"
[[mods]] #mandatory
modId="jamswom" #mandatory
version="20.9.3" #mandatory
displayName="Reverie's Weapons Of Miracles Rebalance" #mandatory
authors="Voidy Jam" #optional
description='''${mod_description}'''

[[dependencies.jamswom]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47.3.10,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.jamswom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.jamswom]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.8.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.jamswom]]
    modId="wom"
    mandatory=true
    versionRange="[20.1.8,)"
    ordering="AFTER"
    side="BOTH"
[[mixins]]
    modid="jamswom"
    config="mixins.jamswom.json"
